project:
  type: website
  output-dir: docs

bibliography: references.bib

website:
  title: "BNFO 420 - Capstone"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: proposal.qmd
        text: Methods                
      - href: results.qmd
        text: Results
      - href: limitations.qmd
        text: Limitations & Future Work
      - href: team.qmd
        text: Team
      - href: references.qmd
        text: Works Cited
  page-footer:
    left: "BNFO 420 • VCU"
    right: "Built with Quarto"

format:
  html:
    theme: journal
    toc: true
    number-sections: true
    embed-resources: true

execute:
  echo: true
  warning: false
  message: false
