---
title: "Works Cited"
---

## References
- CARMIL3 capping protein regulator and myosin 1 linker 3 [Homo sapiens (human)] - Gene - NCBI. (2026). Nih.gov. https://www.ncbi.nlm.nih.gov/gene/90668
- Chen, Long & Tong, Xingyan & Wu, Yujie & Liu, Can & Tang, Chuang & Qi, Xu & Kong, Fanli & Li, Mingzhou & Jin, Long & Zeng, Bo. (2025). A dataset of single-cell transcriptomic atlas of Bama pig and potential marker genes across seven tissues. BMC Genomic Data. 26. 10.1186/s12863-025-01308-3. 
- Chen L, Tong X, Wu Y, Liu C et al. A dataset of single-cell transcriptomic atlas of Bama pig and potential marker genes across seven tissues. BMC Genom Data 2025 Mar 12;26(1):16. PMID: 40075302

- Cho, H., Zhao, X., Hatori, M., Yu, R. T., Barish, G. D., Lam, M. T., Chong, L.-W., DiTacchio, L., Atkins, A. R., Glass, C. K., Liddle, C., Auwerx, J., Downes, M., Panda, S., & Evans, R. M. (2012). Regulation of circadian behaviour and metabolism by REV-ERB-α and REV-ERB-β. Nature, 485(7396), 123–127. https://doi.org/10.1038/nature11048

- Fisk HL, Childs CE, Miles EA, Ayres R et al. Dysregulation of endocannabinoid concentrations in human subcutaneous adipose tissue in obesity and modulation by omega-3 polyunsaturated fatty acids. Clin Sci (Lond) 2021 Jan 15;135(1):185-200. PMID: 33393630

- Fisk HL, Childs CE, Miles EA, Ayres R et al. Modification of subcutaneous white adipose tissue inflammation by omega-3 fatty acids is limited in human obesity-a double blind, randomised clinical trial. EBioMedicine 2022 Mar;77:103909. PMID: 35247847

- Gene - OXA1L. (2016). Maayanlab.cloud; Harmonizome. https://maayanlab.cloud/Harmonizome/gene/OXA1L

- Kogelman LJ, Cirera S, Zhernakova DV, Fredholm M et al. Identification of co-expression gene networks, regulatory genes and pathways for obesity based on adipose tissue RNA Sequencing in a porcine model. BMC Med Genomics 2014 Sep 30;7:57. PMID: 25270054

- Kogelman LJ, Zhernakova DV, Westra HJ, Cirera S et al. An integrative systems genetics approach reveals potential causal genes and pathways related to obesity. Genome Med 2015 Oct 20;7:105. PMID: 26482556

- Litten-Brown, J. C., Corson, A. M., & Clarke, L. (2010). Porcine models for the metabolic syndrome, digestive and bone disorders: a general overview. Animal : an international journal of animal bioscience, 4(6), 899–920. https://doi.org/10.1017/S1751731110000200

- Liberzon, A., Birger, C., Thorvaldsdóttir, H., Ghandi, M., Mesirov, Jill P., & Tamayo, P. (2015). The Molecular Signatures Database Hallmark Gene Set Collection. Cell Systems, 1(6), 417–425. https://doi.org/10.1016/j.cels.2015.12.004

- Lu, Y.-H., Olof Stefan Dallner, Kivanc Birsoy, Gulya Fayzikhodjaeva, & Friedman, J. M. (2015). Nuclear Factor-Y is an adipogenic factor that regulates leptin gene expression. Molecular Metabolism, 4(5), 392–405. https://doi.org/10.1016/j.molmet.2015.02.002

- Manna, P., & Jain, S. K. (2015). Obesity, Oxidative Stress, Adipose Tissue Dysfunction, and the Associated Health Risks: Causes and Therapeutic Strategies. Metabolic Syndrome and Related Disorders, 13(10), 423–444. https://doi.org/10.1089/met.2015.0095

- Ostedgaard, L. S., Price, M. P., Whitworth, K. M., Abou Alaiwa, M. H., Fischer, A. J., Warrier, A., Samuel, M., Spate, L. D., Allen, P. D., Hilkin, B. M., Romano Ibarra, G. S., Ortiz Bezara, M. E., Goodell, B. J., Mather, S. E., Powers, L. S., Stroik, M. R., Gansemer, N. D., Hippee, C. E., Zarei, K., & Goeken, J. A. (2020). Lack of airway submucosal glands impairs respiratory host defenses. ELife, 9, e59653. https://doi.org/10.7554/eLife.59653

- Savova, M. S., Mihaylova, L. V., Tews, D., Wabitsch, M., & Georgiev, M. I. (2023). Targeting PI3K/AKT signaling pathway in obesity. Biomedicine & Pharmacotherapy, 159, 114244. https://doi.org/10.1016/j.biopha.2023.114244

- Spurlock, M. E., & Gabler, N. K. (2008). The development of porcine models of obesity and the metabolic syndrome. The Journal of nutrition, 138(2), 397–402. https://doi.org/10.1093/jn/138.2.397

- Tuggle, C. K., Wang, Y., & Couture, O. (2007). Advances in swine transcriptomics. International journal of biological sciences, 3(3), 132–152. https://doi.org/10.7150/ijbs.3.132

- Wen, X., Zhang, B., Wu, B., Xiao, H., Li, Z., Li, R., Xu, X., & Li, T. (2022). Signaling pathways in obesity: mechanisms and therapeutic interventions. Signal Transduction and Targeted Therapy, 7(1). https://doi.org/10.1038/s41392-022-01149-x
